# syntax=docker/dockerfile:1.2
## używam wieloetapowego budowania obrazów
## automatyczne dobranie obrazu dla platformy, dla której budujemy
FROM --platform=$BUILDPLATFORM node:alpine as builder

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build
###########

FROM node:alpine as runner
ENV NODE_ENV=production
ENV NODE_OPTIONS=--openssl-legacy-provider

COPY --from=builder /app/public /app/public
WORKDIR /app
#RUN npm install
#CMD ["node", "index.js"]
EXPOSE 3000
CMD ["index.js"]